apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: printer
spec:
  params:
    - name: commands
      type: array
      default:
        - Hello, I am the default value
  image: ubuntu
  args: ["$(params.commands)"]
  script: |
    #!/usr/bin/env sh
    set -eu

    # Print output
    for command in "$@"; do
          echo "$command"
    done
